sudo: required

services:
    - docker

before_install:
    - docker build -t gabriel-delira/docker-react-study -f Dockerfile.dev .

scripts:
    - docker run -e CI=true gabriel-delira/docker-react-study npm run test